[deps]
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
QuantumLangBase = "da95bb62-cf3d-408c-9e0f-d289a8effce0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1"
